#pragma config(Motor,  port2,           flywheelLeft,  tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           flywheelRight, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           intakeSystem,  tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           conveyerBelt,  tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           leftBackWheel, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port7,           leftFrontWheel, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port8,           rightBackWheel, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port9,           rightFrontWheel, tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// motor(flywheelLeft)= 127 ;
	// motor(flywheelRight)= 100 ;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		//Flywheel Left (Top)
		if(vexRT[Btn6UXmtr2] == 1)
		{
		motor[flywheelLeft] = 127;
		}

		if(vexRT[Btn6UXmtr2] == 0)
		{
		motor[flywheelLeft] = 0;
		}

		if(vexRT[Btn6UXmtr2] == 1)
		{
		motor[flywheelLeft] = 127;

		}
		if(vexRT[Btn6UXmtr2] == 0)
		{
		motor[flywheelLeft] = 0;
		}
		//Intake System Individual
		if(vexRT[Btn6U] == 1)
		{
			motor[intakeSystem] = 127;
		}
		if(vexRT[Btn6U] == 0)
		{
			motor[intakeSystem] = 0;
		}
		//Conveyer Belt Individual
		if(vexRT[Btn6UXmtr2] == 1)
		{
			motor[conveyerBelt] = -60;
		}
		if(vexRT[Btn6UXmtr2] == 0)
		{
			motor[conveyerBelt] = 0;
		}
		// Flywheel Setting 1
		if(vexRT[Btn8UXmtr2] == 1)
		{
		//	motor[flywheelLeft] = 0;
			motor[flywheelRight] = 75;
		}
		if(vexRT[Btn8UXmtr2] == 0)
		{
		//	motor[flywheelLeft] = 0;
			motor[flywheelRight] = 0;
		}
		// Flywheel Setting 2
		if(vexRT[Btn8LXmtr2] == 1)
		{
			//motor[flywheelLeft] = 0;
			motor[flywheelRight] = 85;
		}
		if(vexRT[Btn8LXmtr2] == 0)
		{
		//	motor[flywheelLeft] = 0;
			motor[flywheelRight] = 0;
		}
		//Flywheel Setting 3
		if(vexRT[Btn8RXmtr2] == 1)
		{
			//motor[flywheelLeft] = 0;
			motor[flywheelRight] = 105;
		}
		if(vexRT[Btn8RXmtr2] == 0)
		{
		//	motor[flywheelLeft] = 0;
			motor[flywheelRight] = 0;
		}
		//Flywheel Setting 4
		if(vexRT[Btn8DXmtr2] == 1)
		{
			//motor[flywheelLeft] = 0;
			motor[flywheelRight] = 255;
		}
		if(vexRT[Btn8DXmtr2] == 0)
		{
			//motor[flywheelLeft] = 0;
			motor[flywheelRight] = 0;
		}


		getJoystickValue(joy1_y1);
		motor[leftBackWheel] = vexRT[Ch3];
		motor[leftFrontWheel] = vexRT[Ch3];

		getJoystickValue(joy1_y2);
		motor[rightFrontWheel] = vexRT[Ch2];
		motor[rightBackWheel] = vexRT[Ch2];
	}
}
