#pragma config(Motor,  port1,           flywheelLeft,  tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port4,           intakeSystem,  tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           conveyerBelt,  tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           leftBackWheel, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port7,           leftFrontWheel, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port8,           rightBackWheel, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port9,           rightFrontWheel, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port10,          flywheelRight, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

task autonomous()
{
	motor(flywheelLeft)= 127 ;
	motor(flywheelRight)= 127 ;
	motor(conveyerBelt) = 127 ;
	
}

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		//Flywheel Left (Top)
		if(vexRT[Btn6UXmtr2] == 1)
		{
		motor[flywheelLeft] = 127;
		}

		if(vexRT[Btn6UXmtr2] == 0)
		{
		motor[flywheelLeft] = 0;
		}

		if(vexRT[Btn6UXmtr2] == 1)
		{
		motor[flywheelRight] = 127;

		}
		if(vexRT[Btn6UXmtr2] == 0)
		{
		motor[flywheelRight] = 0;
		}
		//Intake System Individual
		if(vexRT[Btn6U] == 1)
		{
			motor[intakeSystem] = 127;
		}
		if(vexRT[Btn6U] == 0)
		{
			motor[intakeSystem] = 0;
		}
		//Conveyer Belt Individual
		if(vexRT[Btn6UXmtr2] == 1)
		{
			motor[conveyerBelt] = -60;
		}
		if(vexRT[Btn6UXmtr2] == 0)
		{
			motor[conveyerBelt] = 0;
		}


		getJoystickValue(joy1_y1);
		motor[leftBackWheel] = vexRT[Ch3];
		motor[leftFrontWheel] = vexRT[Ch3];

		getJoystickValue(joy1_y2);
		motor[rightFrontWheel] = vexRT[Ch2];
		motor[rightBackWheel] = vexRT[Ch2];
	}
}
